name: Báo cáo lỗi
description: Phản hồi lỗi hoặc vấn đề của plugin này
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## Chào mừng đến với trình theo dõi vấn đề của SlimefunGuguProject
        Bạn đang báo cáo lỗi xuất hiện trong bản Supreme.
        Mọi ý kiến, đề xuất vui lòng truy cập [QQ Group](https://50l.cc/gugu-qgroup) để phản hồi.
        Nên đọc [bài viết này](https://slimefun-wiki.guizhanss.cn/How-to-report-bugs) để hiểu cách báo cáo lỗi đúng cách.

        <strong><i>Bạn phải điền các mục được đánh dấu sao (*)</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Mục kiểm tra
      description: Trước khi báo cáo, bạn cần xác nhận
      options:
        - label: Bạn đang sử dụng phiên bản tải từ trang build
          required: true
        - label: Bạn đã kiểm tra checksum của tệp đã tải, xác nhận tệp đã được tải đầy đủ
          required: true
        - label: Bạn không thực hiện bất kỳ thay đổi nào với nội dung tệp đã tải
          required: true
        - label: Bạn đã tìm kiếm [danh sách vấn đề đã biết](https://github.com/SlimefunGuguProject/Supreme/issues) và không tìm thấy vấn đề tương tự
          required: true

  - type: textarea
    id: description
    attributes:
      label: Mô tả vấn đề
      description: |
        Mô tả chi tiết vấn đề bạn muốn báo cáo
        Cung cấp thông tin chi tiết giúp chúng tôi xử lý vấn đề nhanh hơn
      placeholder: Chỉ nói "không dùng được" không thể giúp nhà phát triển xác định vấn đề.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Các bước tái hiện
      description: |
        Vui lòng mô tả chi tiết cách tái hiện vấn đề này
        Nếu có video, vui lòng cung cấp liên kết video tại đây
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Hành vi mong đợi
      description: |
        Bạn nghĩ điều gì sẽ xảy ra
        Đôi khi, nguyên nhân vấn đề là bạn hiểu sai chức năng nào đó.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Nhật ký máy chủ
      description: |
        Vui lòng kiểm tra nhật ký máy chủ xem có bất kỳ lỗi nào không, nếu có hãy tải lên [https://paste.guizhanss.net/](https://paste.guizhanss.net/) và điền liên kết vào đây.
        **Không dán trực tiếp nhật ký vào đây**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Báo cáo lỗi
      description: |
        Nếu nhật ký máy chủ đề cập đến tệp trong `/plugins/Slimefun/error-reports` (báo cáo lỗi)
        Vui lòng tải lên [https://paste.guizhanss.net/](https://paste.guizhanss.net/) và điền liên kết vào đây.
        **Không dán trực tiếp báo cáo lỗi vào đây**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Phần mềm máy chủ
      description: Vui lòng chọn phần mềm máy chủ bạn đang sử dụng
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Khác (vui lòng ghi rõ trong mô tả vấn đề)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Phiên bản Minecraft
      description: Vui lòng điền phiên bản Minecraft của bạn
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Phiên bản Slimefun
      description: |
        Vui lòng điền phiên bản Slimefun
        (ví dụ v4.9-canary-08120db)
        Nếu bạn có quyền quản trị viên, hãy chạy lệnh `/sf versions`, chụp ảnh màn hình và tải lên **toàn bộ nội dung** đầu ra của lệnh.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Phiên bản plugin
      description: |
        Vui lòng điền phiên bản plugin
        (ví dụ Build 1 (git x114514))
    validations:
      required: true
