blank_issues_enabled: false
contact_links:
  - name: Không có tài khoản Github? Không biết sử dụng Github?
    url: https://50l.cc/gugu-qgroup
    about: Nhấp vào nút bên phải để tham gia nhóm QQ và phản hồi
